before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: lMp+fkd82/BKCReROn/B1chhKCN1NBhbJjVb5BmOs0s5qkNCOxmxOJLGehjma7ysJKmi3sZ6/SjFc7xcBKuON+TgkFXgr9a+b9RDmuT4ntpHgUEjHkWPIHYS8kLZ0ZH442SeD9RgUzEQaxNaXs5Lh0v70M/rV8Ya4Ww3SMVL/3NvGCzNCFx3OgxCaBsFAbCX9sLYPGUFBPB/7tAG84xTR8yk4tEW9mL3w83a3bZlj9CsNqGd3A+ufG3UeoftNnuxTh2yRjI2h49vNQRUmq6JE69zIe3NLged23+zkstxZlA2yftniZaH8p/FIUQipOkComibaBSxMDLvIx+eMzVZHaJFGpmq9psUB58HkSD+nJRDb+iqzAIXs1anpvBBKxh81Ql63FzXx4M4ZNDeE3AZPXUl7zJUQz96XSF6+w53JPZm8LaZrbS8ytuNsPkwFNMJi2Le3WleLzl13JdKG4RHkR+xdLzeWLNaPEQCfvOYqrytwldvSAvgGK9OW4ompxhNki/WQJw7TAkRipTYEiIkBDimxysFHOFZCbP9Y2XSn8s2hNvlqFw2jYp5xS2aYhaqMfBO3l3QNmY6FhEwrlPkK7/22yLsKlh6XZhyfNiJqCCWRLYquQm/kxTAagl71bxl3Oh/nszj8Wd13VXG3jDhUbfdxVCfK2JpnxnzPy3OzVc= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
